//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EohiDataServerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_3d_scene
    {
        public int id { get; set; }
        public string scenenid { get; set; }
        public string scenename { get; set; }
        public string scenenote { get; set; }
        public string scenetype { get; set; }
        public string scenecfg { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> edittime { get; set; }
    }
}
