//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EohiDataServerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_3d_model_files
    {
        public int id { get; set; }
        public string fileName { get; set; }
        public Nullable<int> fileSize { get; set; }
        public string fileSuffix { get; set; }
        public Nullable<System.DateTime> uploadTime { get; set; }
        public string uploadUser { get; set; }
        public string fileUrl { get; set; }
        public Nullable<System.DateTime> editTime { get; set; }
        public string editUser { get; set; }
        public string modelIdentity { get; set; }
        public string modelName { get; set; }
        public Nullable<int> modelId { get; set; }
    }
}
