//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EohiDataServerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_flowchart_node_switchitem
    {
        public int id { get; set; }
        public string flowchart_id { get; set; }
        public string node_id { get; set; }
        public string switchid { get; set; }
        public string switchname { get; set; }
        public string switchnote { get; set; }
    }
}
