//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EohiDataServerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_user
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public string user_name { get; set; }
        public string user_password { get; set; }
        public Nullable<int> user_allow { get; set; }
        public string remark { get; set; }
        public string user_roles { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
    }
}
