//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EohiDataServerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_webapp
    {
        public int id { get; set; }
        public string webappname { get; set; }
        public string webappnote { get; set; }
        public string webapphtml { get; set; }
        public string webappscript { get; set; }
        public string mod_man { get; set; }
        public Nullable<System.DateTime> mod_date { get; set; }
    }
}
