//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EohiDataServerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_flowchart_instance
    {
        public int id { get; set; }
        public string flowchart_id { get; set; }
        public string flowchart_version { get; set; }
        public string instance_id { get; set; }
        public Nullable<System.DateTime> cre_date { get; set; }
        public string cre_man { get; set; }
        public string instance_status { get; set; }
        public string instance_message { get; set; }
    }
}
