//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EohiDataServerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_type_htmlhelp
    {
        public int id { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string HtmlStr { get; set; }
        public string Remarks { get; set; }
    }
}
