//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EohiDataServerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_3d_models
    {
        public int id { get; set; }
        public string modelIdentity { get; set; }
        public string modelName { get; set; }
        public string modeDescription { get; set; }
        public string modelRemark { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string createUser { get; set; }
        public string modelVersion { get; set; }
        public Nullable<System.DateTime> editTime { get; set; }
        public string editUser { get; set; }
        public Nullable<System.DateTime> yujiPutTime { get; set; }
        public string modelImage { get; set; }
        public string modelForOutfit { get; set; }
        public string modeltype { get; set; }
        public string modelurl { get; set; }
    }
}
